export const createLayoutPlaceholder = ({
  placeholderId,
  x,
  y,
  width,
  height,
  type = "text",
  role = "body",
  padding = "8px",
  background = "#FFFFFF00",
  formatting = {},
}) => ({
  "placeholder-id": placeholderId,
  position: { x, y },
  width,
  height,
  padding: { css: padding },
  type,
  role,
  background,
  formatting,
});

export const createDefaultLayouts = ({ titleFormatting, bodyFormatting }) => {
  const makeTitleTop = () =>
    createLayoutPlaceholder({
      placeholderId: "title-placeholder",
      x: 120,
      y: 80,
      width: 1040,
      height: 90,
      type: "text",
      role: "title",
      formatting: titleFormatting,
    });

  const makeBodyFull = () =>
    createLayoutPlaceholder({
      placeholderId: "body-placeholder",
      x: 120,
      y: 220,
      width: 1040,
      height: 360,
      type: "text",
      role: "body",
      padding: "12px",
      formatting: bodyFormatting,
    });

  const makeBodyLeft = () =>
    createLayoutPlaceholder({
      placeholderId: "body-placeholder",
      x: 120,
      y: 220,
      width: 560,
      height: 360,
      type: "text",
      role: "body",
      padding: "12px",
      formatting: bodyFormatting,
    });

  const makeMediaRight = () =>
    createLayoutPlaceholder({
      placeholderId: "media-placeholder",
      x: 760,
      y: 220,
      width: 360,
      height: 240,
      type: "image",
      role: "body",
      padding: "0px",
    });

  const makeLeftColumn = () =>
    createLayoutPlaceholder({
      placeholderId: "body-placeholder",
      x: 120,
      y: 220,
      width: 470,
      height: 360,
      type: "text",
      role: "body",
      padding: "12px",
      formatting: bodyFormatting,
    });

  const makeRightColumn = () =>
    createLayoutPlaceholder({
      placeholderId: "right-body-placeholder",
      x: 690,
      y: 220,
      width: 470,
      height: 360,
      type: "text",
      role: "body",
      padding: "12px",
      formatting: bodyFormatting,
    });

  return [
    {
      "layout-id": "title-content",
      placeholders: [makeTitleTop(), makeBodyFull()],
    },
    {
      "layout-id": "title-content-media",
      placeholders: [makeTitleTop(), makeBodyLeft(), makeMediaRight()],
    },
    {
      "layout-id": "two-columns",
      placeholders: [makeTitleTop(), makeLeftColumn(), makeRightColumn()],
    },
    {
      "layout-id": "title-only",
      placeholders: [makeTitleTop()],
    },
    {
      "layout-id": "blank",
      placeholders: [],
    },

    // {
    //   "layout-id": "title",
    //   placeholders: [
    //     createLayoutPlaceholder({
    //       placeholderId: "title-placeholder",
    //       x: 75,
    //       y: 80,
    //       width: 700,
    //       height: 290,
    //       type: "text",
    //       role: "title",
    //       formatting: titleFormatting,
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "body-placeholder",
    //       x: 75,
    //       y: 410,
    //       width: 560,
    //       height: 160,
    //       type: "text",
    //       role: "body",
    //       padding: "12px",
    //       formatting: bodyFormatting,
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "media-placeholder",     
    //       x: 920,
    //       y: 0,
    //       width: 360,
    //       height: 420,
    //       type: "image",
    //       role: "body",
    //       padding: "0px",
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "media-placeholder-2",   
    //       x: 920,
    //       y: 430,
    //       width: 180,
    //       height: 290,
    //       type: "image",
    //       role: "body",
    //       padding: "0px",
    //     }),
    //   ],
    // },
    // {
    //   "layout-id": "agenta",
    //   placeholders: [
    //     createLayoutPlaceholder({
    //       placeholderId: "media-placeholder",       
    //       x: 0,
    //       y: 0,
    //       width: 460,
    //       height: 720,
    //       type: "image",
    //       role: "body",
    //       padding: "0px",
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "label-placeholder",      
    //       x: 1140,
    //       y: 40,
    //       width: 120,
    //       height: 45,
    //       type: "text",
    //       role: "body",
    //       formatting: bodyFormatting,
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "title-placeholder",       
    //       x: 510,
    //       y: 175,
    //       width: 750,
    //       height: 75,
    //       type: "text",
    //       role: "title",
    //       formatting: titleFormatting,
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "body-placeholder",        
    //       x: 510,
    //       y: 270,
    //       width: 750,
    //       height: 430,
    //       type: "text",
    //       role: "body",
    //       padding: "12px",
    //       formatting: bodyFormatting,
    //     }),
    //   ],
    // },
    // {
    //   "layout-id": "text-with-graphic",
    //   placeholders: [
    //     createLayoutPlaceholder({
    //       placeholderId: "label-placeholder",
    //       x: 1140,
    //       y: 40,
    //       width: 120,
    //       height: 45,
    //       type: "text",
    //       role: "body",
    //       formatting: bodyFormatting,
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "title-placeholder",
    //       x: 215,
    //       y: 85,
    //       width: 445,
    //       height: 155,
    //       type: "text",
    //       role: "title",
    //       formatting: titleFormatting,
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "body-placeholder",
    //       x: 215,
    //       y: 260,
    //       width: 445,
    //       height: 445,
    //       type: "text",
    //       role: "body",
    //       padding: "12px",
    //       formatting: bodyFormatting,
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "right-body-placeholder",
    //       x: 775,
    //       y: 180,
    //       width: 485,
    //       height: 520,
    //       type: "text",
    //       role: "body",
    //       padding: "12px",
    //       formatting: bodyFormatting,
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "footer-placeholder",
    //       x: 970,
    //       y: 678,
    //       width: 280,
    //       height: 35,
    //       type: "text",
    //       role: "body",
    //       formatting: bodyFormatting,
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "page-number-placeholder",
    //       x: 1255,
    //       y: 678,
    //       width: 40,
    //       height: 35,
    //       type: "text",
    //       role: "body",
    //       formatting: bodyFormatting,
    //     }),
    //   ],
    // },
    // {
    //   "layout-id": "title-content-footer",
    //   placeholders: [
    //     createLayoutPlaceholder({
    //       placeholderId: "title-placeholder",
    //       x: 155,
    //       y: 80,
    //       width: 1065,
    //       height: 100,
    //       type: "text",
    //       role: "title",
    //       formatting: titleFormatting,
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "body-placeholder",
    //       x: 155,
    //       y: 215,
    //       width: 1065,
    //       height: 500,
    //       type: "text",
    //       role: "body",
    //       padding: "12px",
    //       formatting: bodyFormatting,
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "footer-placeholder",
    //       x: 985,
    //       y: 678,
    //       width: 265,
    //       height: 35,
    //       type: "text",
    //       role: "body",
    //       formatting: bodyFormatting,
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "page-number-placeholder",
    //       x: 1255,
    //       y: 678,
    //       width: 40,
    //       height: 35,
    //       type: "text",
    //       role: "body",
    //       formatting: bodyFormatting,
    //     }),
    //   ],
    // },
    // {
    //   "layout-id": "two-columns-footer",
    //   placeholders: [
    //     createLayoutPlaceholder({
    //       placeholderId: "title-placeholder",
    //       x: 155,
    //       y: 80,
    //       width: 1065,
    //       height: 100,
    //       type: "text",
    //       role: "title",
    //       formatting: titleFormatting,
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "body-placeholder",
    //       x: 155,
    //       y: 215,
    //       width: 530,
    //       height: 505,
    //       type: "text",
    //       role: "body",
    //       padding: "12px",
    //       formatting: bodyFormatting,
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "right-body-placeholder",
    //       x: 710,
    //       y: 215,
    //       width: 530,
    //       height: 505,
    //       type: "text",
    //       role: "body",
    //       padding: "12px",
    //       formatting: bodyFormatting,
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "footer-placeholder",
    //       x: 985,
    //       y: 678,
    //       width: 265,
    //       height: 35,
    //       type: "text",
    //       role: "body",
    //       formatting: bodyFormatting,
    //     }),
    //     createLayoutPlaceholder({
    //       placeholderId: "page-number-placeholder",
    //       x: 1255,
    //       y: 678,
    //       width: 40,
    //       height: 35,
    //       type: "text",
    //       role: "body",
    //       formatting: bodyFormatting,
    //     }),
    //   ],
    // },
  ];
};