const createEventId = () => crypto.randomUUID();

export const EditorEventType = {
  PRESENTATION: {
    CREATE: "CREATE_PRESENTATION",
    UPDATE: "UPDATE_PRESENTATION", 
    SAVE: "SAVE_PRESENTATION",
    LOAD: "LOAD_PRESENTATION",
    EXPORT: "EXPORT_PRESENTATION",
    TOGGLE_AUTOSAVE: "PRESENTATION.TOGGLE_AUTOSAVE",
  },

  MASTER: {
    UPDATE_THEME: "UPDATE_MASTER_THEME",        
    UPDATE_DIMENSIONS: "UPDATE_MASTER_DIMENSIONS",
    UPDATE_FORMATTING: "UPDATE_MASTER_FORMATTING",
  },

  LAYOUT: {
    ADD: "ADD_LAYOUT",
    DELETE: "DELETE_LAYOUT",
    APPLY: "APPLY_LAYOUT",
    UPDATE: "UPDATE_LAYOUT",
    ADD_PLACEHOLDER: "ADD_PLACEHOLDER",
    UPDATE_PLACEHOLDER: "UPDATE_PLACEHOLDER",
    DELETE_PLACEHOLDER: "DELETE_PLACEHOLDER",
  },

  SLIDE: {
    ADD: "ADD_SLIDE",
    DELETE: "DELETE_SLIDE",
    DUPLICATE: "DUPLICATE_SLIDE",
    SELECT: "SELECT_SLIDE",
    REORDER: "REORDER_SLIDES",
    TOGGLE_HIDDEN: "TOGGLE_SLIDE_HIDDEN",      
    UPDATE_BACKGROUND: "UPDATE_SLIDE_BACKGROUND",
    UPDATE_TRANSITION: "UPDATE_SLIDE_TRANSITION",
    UPDATE_NOTES: "UPDATE_SLIDE_NOTES",
  },

  CONTENT: {
      ADD_TEXT: "ADD_TEXT",
      UPDATE_TEXT: "UPDATE_TEXT",
      UPDATE_TEXT_COMMIT: "UPDATE_TEXT_COMMIT",

      MOVE_ELEMENT: "MOVE_ELEMENT",
      MOVE_ELEMENT_COMMIT: "MOVE_ELEMENT_COMMIT",

      RESIZE_ELEMENT: "RESIZE_ELEMENT",
      RESIZE_ELEMENT_COMMIT: "RESIZE_ELEMENT_COMMIT",

      UPDATE_ELEMENT: "UPDATE_ELEMENT",
      UPDATE_ELEMENT_COMMIT: "UPDATE_ELEMENT_COMMIT",

      DELETE_ELEMENT: "DELETE_ELEMENT",
      UPDATE_TEXT_FORMATTING: "UPDATE_TEXT_FORMATTING",
  },

  MEDIA: {
    ADD: "ADD_MEDIA",             
    UPDATE: "UPDATE_MEDIA",
    UPDATE_COMMIT: "UPDATE_MEDIA_COMMIT",
    DELETE: "DELETE_MEDIA",
  },

  ANIMATION: {
    ADD: "ANIMATION.ADD",
    UPDATE: "ANIMATION.UPDATE",
    DELETE: "ANIMATION.DELETE",
  },

  HISTORY: {
    UNDO: "HISTORY.UNDO",
    REDO: "HISTORY.REDO"
  }
};

export const createEditorEvent = (type, payload = {}) => ({
  id: createEventId(),
  type,
  payload,
  timestamp: Date.now(),
});