export const EditorEventType = {
  PRESENTATION: {
    CREATE: "PRESENTATION.CREATE",
    SAVE: "PRESENTATION.SAVE",
    LOAD: "PRESENTATION.LOAD",
    TOGGLE_AUTOSAVE: "PRESENTATION.TOGGLE_AUTOSAVE",
  },

  MASTER: {
    UPDATE_THEME: "MASTER.UPDATE_THEME",
    UPDATE_DIMENSIONS: "MASTER.UPDATE_DIMENSIONS",
    UPDATE_FORMATTING: "MASTER.UPDATE_FORMATTING",
    ADD_ELEMENT: "MASTER.ADD_ELEMENT",
    UPDATE_ITEM: "MASTER.UPDATE_ITEM",
    DELETE_ELEMENT: "MASTER.DELETE_ELEMENT",
    TOGGLE_TITLE: "MASTER.TOGGLE_TITLE",
    TOGGLE_FOOTERS: "MASTER.TOGGLE_FOOTERS",
  },

  LAYOUT: {
    ADD: "LAYOUT.ADD",
    DELETE: "LAYOUT.DELETE",
    APPLY: "LAYOUT.APPLY",
    UPDATE_PLACEHOLDERS: "LAYOUT.UPDATE_PLACEHOLDERS",
    RESET: "LAYOUT.RESET",
    RENAME: "LAYOUT.RENAME",
    ADD_ELEMENT: "LAYOUT.ADD_ELEMENT",
    DELETE_ELEMENT: "LAYOUT.DELETE_ELEMENT",
    ADD_PLACEHOLDER: "LAYOUT.ADD_PLACEHOLDER",
    DELETE_PLACEHOLDER: "LAYOUT.DELETE_PLACEHOLDER",
    UPDATE_FONT: "LAYOUT.UPDATE_FONT",
    UPDATE_ITEM: "LAYOUT.UPDATE_ITEM",
    UPDATE_TEXT_FORMATTING: "LAYOUT.UPDATE_TEXT_FORMATTING",
  },

  SLIDE: {
    ADD: "SLIDE.ADD",
    DELETE: "SLIDE.DELETE",
    DUPLICATE: "SLIDE.DUPLICATE",
    SELECT: "SLIDE.SELECT",
    REORDER: "SLIDE.REORDER",
    TOGGLE_HIDDEN: "SLIDE.TOGGLE_HIDDEN",
    UPDATE_BACKGROUND: "SLIDE.UPDATE_BACKGROUND",
    UPDATE_TRANSITION: "SLIDE.UPDATE_TRANSITION",
    UPDATE_NOTES: "SLIDE.UPDATE_NOTES",
    APPLY_TRANSITION_TO_ALL: "SLIDE.APPLY_TRANSITION_TO_ALL",
    APPLY_BACKGROUND_TO_ALL: "SLIDE.APPLY_BACKGROUND_TO_ALL",
  },

  TEXT: {
    ADD: "TEXT.ADD",
    UPDATE_CONTENT: "TEXT.UPDATE_CONTENT",
    UPDATE_FORMATTING: "TEXT.UPDATE_FORMATTING",
    UPDATE_PARAGRAPH_FORMATTING: "TEXT.UPDATE_PARAGRAPH_FORMATTING",
    UPDATE_PARAGRAPHS: "TEXT.UPDATE_PARAGRAPHS",
    UPDATE_RANGE_FORMATTING: "TEXT.UPDATE_RANGE_FORMATTING",
    UPDATE_RUN_LINK: "TEXT.UPDATE_RUN_LINK",
    DELETE: "TEXT.DELETE",
  },

  ELEMENT: {
    SELECT: "ELEMENT.SELECT",
    RESIZE: "ELEMENT.RESIZE",
    UPDATE: "ELEMENT.UPDATE",
    UPDATE_SILENT: "ELEMENT.UPDATE_SILENT",
    UPDATE_MANY: "ELEMENT.UPDATE_MANY",
    COPY: "ELEMENT.COPY",
    PASTE: "ELEMENT.PASTE",
    CUT: "ELEMENT.CUT",
    DELETE_SELECTION: "ELEMENT.DELETE_SELECTION",
  },

  MEDIA: {
    ADD: "MEDIA.ADD",
    UPDATE: "MEDIA.UPDATE",
    DELETE: "MEDIA.DELETE",
  },

  COMMENT: {
    ADD: "COMMENT.ADD",
    DELETE: "COMMENT.DELETE",
  },

  FONT: {
    ADD: "FONT.ADD",
    DELETE: "FONT.DELETE",
  },

  ANIMATION: {
    ADD: "ANIMATION.ADD",
    UPDATE: "ANIMATION.UPDATE",
    DELETE: "ANIMATION.DELETE",
  },

  FORMAT_PAINTER: {
    COPY: "FORMAT_PAINTER.COPY",
    PASTE: "FORMAT_PAINTER.PASTE",
  },

  HISTORY: {
    BEGIN: "HISTORY.BEGIN",
    COMMIT: "HISTORY.COMMIT",
    CANCEL: "HISTORY.CANCEL",
    UNDO: "HISTORY.UNDO",
    REDO: "HISTORY.REDO",
  },
};

export const createEditorEvent = (type, payload = {}) => ({ type, payload });
